sudo: required
services:
- docker

branches:
  only:
  - master

matrix:
  include:
  - name: PHP 7.2
    env: BUILD_ENV=php7.2
  - name: PHP 7.2 low deps
    env: BUILD_ENV=php7.2 DEPS=low
  - name: PHP 7.1
    env: BUILD_ENV=php7.1
  - name: PHP 7.1 low deps
    env: BUILD_ENV=php7.1 DEPS=low

cache:
  directories:
  - $HOME/.composer/cache

install:
- |
  if [[ ! $DEPS ]]; then
      make composer-install
  elif [[ $DEPS = 'dev' ]]; then
      make composer-install-dev
  elif [[ $DEPS = 'low' ]]; then
      make composer-install-lowest
  fi

script:
- make ci
