name: "Continuous Integration"
on:
    pull_request:
    push:
        branches:
            - "master"

env:
    DOCQA_DOCKER_COMMAND: " "
    DOCQA_DOCKER_IMAGE: dkarlovi/docqa:latest
    PHPQA_DOCKER_COMMAND: " "
    PHPQA_DOCKER_IMAGE: jakzal/phpqa:1.29

jobs:
    MutationTest:
        container: ${{ env.PHPQA_DOCKER_IMAGE }}-${{ matrix.php }}-alpine
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [php7.2, php7.3, php7.4]
                dependencies: [lowest, highest]
        steps:
            -   uses: actions/checkout@master
            -   name: Composer install lowest dependencies
                if: "matrix.dependencies == 'lowest'"
                run: make composer-bare-install-lowest
            -   name: Composer install highest dependencies
                if: "matrix.dependencies == 'highest'"
                run: make composer-bare-install
            -   name: Run tests
                run: make test
    CodeQualityAnalysis:
        container: ${{ env.PHPQA_DOCKER_IMAGE }}-php7.4-alpine
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   name: Composer install highest dependencies
                run: make composer-bare-install
            -   name: Run code quality analysis
                run: make check
    DocumentationQualityAnalysis:
        container: ${{ env.DOCQA_DOCKER_IMAGE }}
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   name: Run documentation quality analysis
                run: make doc
